import React from 'react'
import HeaderComponents from '../layouts/HeaderComponents'
import FooterComponents from '../layouts/FooterComponents'

function HomeComponents() {
  return (
    <React.Fragment>
      <HeaderComponents/>
        <div>
        <div className="loader_bg">
          <div className="splash-logo">
            <img src="https://www.trinity.edu.np/assets/frontend/img/loader-logo.png" alt="Trinity College" />
          </div>
          <h4 className="text-danger">Trinity International College</h4>
        </div>
        <div className="nav-side bg-white show">
          <div className="nav-side--wrap">
            <div className="nav-logo">
              <img src="https://www.trinity.edu.np/assets/backend/uploads/Logo/trinity college logo.jpg" alt="Trinity College" title="Trinity College" className="img-fluid" />
              <button className="navbar-toggler" type="button" id="toggle-menu2">
                <i className="fas fa-angle-left" />
              </button>
            </div>
            <div className="nav-side--info bg-warning">
              <span>Education for the Future</span>
            </div>
            <ul className="list-inline bg-danger ul-item mb-0">
              <li className="nav-item homepage-search">
                <form action="https://www.trinity.edu.np/search" className="w-100 d-flex nav-top--search position-relative" id="main-search_">
                  <input className="form-control" type="search" id="main-search-submit_" placeholder="Search" aria-label="Search" />
                  <button type="submit" className="btn search-icon">
                    <i className="fas fa-search" />
                  </button>
                </form>
              </li>
              <li className="dropdown-menus">
                <a href="https://www.trinity.edu.np/about-trinity"><i className="fas fa-graduation-cap me-2" />About Trinity</a><ul className="nav-items"><li className="dropdown-menus">
                    <a href="javascript:void(0)"> About Us</a><ul className="nav-items"><li><a href="https://www.trinity.edu.np/about-trinity"> Introduction </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/our-legacy"> Our Legacy </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/facts-figures"> Facts &amp; Figures </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/timeline"> Timeline </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/college-environment"> College Environment </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/safety"> Safety </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/trinity-in-the-community"> Trinity in the Community </a></li></ul></li><ul className="nav-items"><li><a href="https://www.trinity.edu.np/about-trinity"> Introduction </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/our-legacy"> Our Legacy </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/facts-figures"> Facts &amp; Figures </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/timeline"> Timeline </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/college-environment"> College Environment </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/safety"> Safety </a></li><li><a href="https://www.trinity.edu.np/about-trinity/about-us/trinity-in-the-community"> Trinity in the Community </a></li></ul><li className="dropdown-menus">
                    <a href="javascript:void(0)"> Messages</a><ul className="nav-items"><li><a href="https://www.trinity.edu.np/about-trinity/messages/ceo"> CEO </a></li><li><a href="https://www.trinity.edu.np/about-trinity/messages/principal"> Principal </a></li><li><a href="https://www.trinity.edu.np/about-trinity/messages/directors"> Directors </a></li><li><a href="https://www.trinity.edu.np/about-trinity/messages/coordinators-plus-two"> Coordinators </a></li></ul></li><ul className="nav-items"><li><a href="https://www.trinity.edu.np/about-trinity/messages/ceo"> CEO </a></li><li><a href="https://www.trinity.edu.np/about-trinity/messages/principal"> Principal </a></li><li><a href="https://www.trinity.edu.np/about-trinity/messages/directors"> Directors </a></li><li><a href="https://www.trinity.edu.np/about-trinity/messages/coordinators-plus-two"> Coordinators </a></li></ul><li className="dropdown-menus">
                    <a href="javascript:void(0)"> Our People</a><ul className="nav-items"><li><a href="https://www.trinity.edu.np/about-trinity/our-people/advisory-board"> Advisory Board</a></li><li><a href="https://www.trinity.edu.np/about-trinity/our-people/board-members"> Board Members </a></li><li><a href="https://www.trinity.edu.np/about-trinity/our-people/faculty"> Faculty </a></li><li><a href="https://www.trinity.edu.np/about-trinity/our-people/staff"> Staff </a></li></ul></li><ul className="nav-items"><li><a href="https://www.trinity.edu.np/about-trinity/our-people/advisory-board"> Advisory Board</a></li><li><a href="https://www.trinity.edu.np/about-trinity/our-people/board-members"> Board Members </a></li><li><a href="https://www.trinity.edu.np/about-trinity/our-people/faculty"> Faculty </a></li><li><a href="https://www.trinity.edu.np/about-trinity/our-people/staff"> Staff </a></li></ul><li className="dropdown-menus">
                    <a href="javascript:void(0)"> On Campus</a><ul className="nav-items"><li><a href="https://www.trinity.edu.np/about-trinity/on-campus/map"> Map </a></li><li><a href="https://www.trinity.edu.np/gallery"> Photo Gallery </a></li><li><a href="https://www.trinity.edu.np/video_gallery"> Video Gallery </a></li><li><a href="https://www.trinity.edu.np/downloads"> Downloads </a></li></ul></li><ul className="nav-items"><li><a href="https://www.trinity.edu.np/about-trinity/on-campus/map"> Map </a></li><li><a href="https://www.trinity.edu.np/gallery"> Photo Gallery </a></li><li><a href="https://www.trinity.edu.np/video_gallery"> Video Gallery </a></li><li><a href="https://www.trinity.edu.np/downloads"> Downloads </a></li></ul></ul></li><li className="dropdown-menus">
                <a href="javascript:void(0)"><i className="fas fa-book me-2" />Academics</a><ul className="nav-items"><li>
                    <a href="http://plustwo.trinity.edu.np/" target="_blank" rel="nofollow"> +2 (NEB)</a>
                  </li><li>
                    <a href="http://alevel.trinity.edu.np/" target="_blank" rel="nofollow"> A Levels</a>
                  </li><li>
                    <a href="http://bachelor.trinity.edu.np/" target="_blank" rel="nofollow"> Bachelor’s</a>
                  </li><li className="dropdown-menus">
                    <a href="javascript:void(0)"> Teaching &amp; Learning</a><ul className="nav-items"><li><a href="https://www.trinity.edu.np/trinity-academics/trinity-teaching-learning/bachelor-teaching"> Teaching Methodology </a></li><li><a href="https://www.trinity.edu.np/trinity-academics/trinity-teaching-learning/online-learning"> Online Learning </a></li><li><a href="https://www.trinity.edu.np/trinity-academics/trinity-teaching-learning/academic-support"> Academic Support </a></li><li><a href="https://www.trinity.edu.np/trinity-academics/trinity-teaching-learning/trinity-collegiate-events"> Collegiate Events </a></li></ul></li><ul className="nav-items"><li><a href="https://www.trinity.edu.np/trinity-academics/trinity-teaching-learning/bachelor-teaching"> Teaching Methodology </a></li><li><a href="https://www.trinity.edu.np/trinity-academics/trinity-teaching-learning/online-learning"> Online Learning </a></li><li><a href="https://www.trinity.edu.np/trinity-academics/trinity-teaching-learning/academic-support"> Academic Support </a></li><li><a href="https://www.trinity.edu.np/trinity-academics/trinity-teaching-learning/trinity-collegiate-events"> Collegiate Events </a></li></ul><li>
                    <a href="https://www.trinity.edu.np/admission/2-features-admission/culture-of-excellence"> Culture of Excellence</a>
                  </li><li>
                    <a href="https://www.trinity.edu.np/academic-calendar"> Academic Calendar</a>
                  </li></ul></li><li className="dropdown-menus">
                <a href="javascript:void(0)"><i className="fa fa-users me-2" />Student Life</a><ul className="nav-items"><li className="dropdown-menus">
                    <a href="https://www.trinity.edu.np/student-life/trinity-facilities"> Facilities</a><ul className="nav-items"><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/library"> Library </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/labs"> Laboratories </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/computer-labs"> ICT Center </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/hostel"> Hostels </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/cafeterias-home"> Cafeterias </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/transportation"> Transportation </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/health-care"> Health Care </a></li><li><a href="http://plustwo.trinity.edu.np/college-facilities/admin/administrative-services" target="_blank" rel="nofollow"> Admin </a></li></ul></li><ul className="nav-items"><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/library"> Library </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/labs"> Laboratories </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/computer-labs"> ICT Center </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/hostel"> Hostels </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/cafeterias-home"> Cafeterias </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/transportation"> Transportation </a></li><li><a href="https://www.trinity.edu.np/facilities/trinity-facilities/health-care"> Health Care </a></li><li><a href="http://plustwo.trinity.edu.np/college-facilities/admin/administrative-services" target="_blank" rel="nofollow"> Admin </a></li></ul><li className="dropdown-menus">
                    <a href="javascript:void(0)"> Clubs &amp; Activities</a><ul className="nav-items"><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/social-services"> Social Services </a></li><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/trinity-intracollege-activities"> Intra-College Activities </a></li><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/intercollege-activities"> Inter-College Activities </a></li><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/excursion-tours"> Excursion &amp; Tours </a></li><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/seminars--workshops--"> Seminars &amp; Workshops </a></li></ul></li><ul className="nav-items"><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/social-services"> Social Services </a></li><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/trinity-intracollege-activities"> Intra-College Activities </a></li><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/intercollege-activities"> Inter-College Activities </a></li><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/excursion-tours"> Excursion &amp; Tours </a></li><li><a href="https://www.trinity.edu.np/student-life/clubs-activities/seminars--workshops--"> Seminars &amp; Workshops </a></li></ul><li>
                    <a href="https://www.trinity.edu.np/publications"> Publications</a>
                  </li><li className="dropdown-menus">
                    <a href="https://www.trinity.edu.np/student-life/counseling-student-life"> Counseling </a><ul className="nav-items"><li><a href="https://www.trinity.edu.np/student-life/counseling-student-life/academic-counseling"> Academic Counseling </a></li><li><a href="https://www.trinity.edu.np/student-life/counseling-student-life/personal-counseling"> Personal Counseling </a></li><li><a href="https://www.trinity.edu.np/student-life/counseling-student-life/motivation-sessions"> Motivation Sessions </a></li></ul></li><ul className="nav-items"><li><a href="https://www.trinity.edu.np/student-life/counseling-student-life/academic-counseling"> Academic Counseling </a></li><li><a href="https://www.trinity.edu.np/student-life/counseling-student-life/personal-counseling"> Personal Counseling </a></li><li><a href="https://www.trinity.edu.np/student-life/counseling-student-life/motivation-sessions"> Motivation Sessions </a></li></ul></ul></li><li className="dropdown-menus">
                <a href="javascript:void(0)"><i className="far fa-file-alt me-2" />Admission</a><ul className="nav-items"><li className="dropdown-menus">
                    <a href="javascript:void(0)"> +2 (NEB)</a><ul className="nav-items"><li><a href="http://plustwo.trinity.edu.np/scholarship/scholarship-overview" target="_blank" rel="nofollow"> Scholarship (+2) </a></li><li><a href="http://plustwo.trinity.edu.np/results" target="_blank" rel="nofollow"> Results (+2) </a></li><li><a href="http://plustwo.trinity.edu.np/placements" target="_blank" rel="nofollow"> Placements (+2) </a></li><li><a href="http://plustwo.trinity.edu.np/testimonials/" target="_blank" rel="nofollow"> Student Views (+2) </a></li></ul></li><ul className="nav-items"><li><a href="http://plustwo.trinity.edu.np/scholarship/scholarship-overview" target="_blank" rel="nofollow"> Scholarship (+2) </a></li><li><a href="http://plustwo.trinity.edu.np/results" target="_blank" rel="nofollow"> Results (+2) </a></li><li><a href="http://plustwo.trinity.edu.np/placements" target="_blank" rel="nofollow"> Placements (+2) </a></li><li><a href="http://plustwo.trinity.edu.np/testimonials/" target="_blank" rel="nofollow"> Student Views (+2) </a></li></ul><li className="dropdown-menus">
                    <a href="javascript:void(0)"> A Levels</a><ul className="nav-items"><li><a href="http://alevel.trinity.edu.np/scholarship/at-admission/entrance-tests-a-level" target="_blank" rel="nofollow"> Scholarship (A Levels) </a></li><li><a href="http://alevel.trinity.edu.np/results" target="_blank" rel="nofollow"> Results (A Levels) </a></li><li><a href="http://alevel.trinity.edu.np/placements" target="_blank" rel="nofollow"> Placements (A Levels) </a></li><li><a href="http://alevel.trinity.edu.np/testimonials/" target="_blank" rel="nofollow"> Student Views (A Level) </a></li></ul></li><ul className="nav-items"><li><a href="http://alevel.trinity.edu.np/scholarship/at-admission/entrance-tests-a-level" target="_blank" rel="nofollow"> Scholarship (A Levels) </a></li><li><a href="http://alevel.trinity.edu.np/results" target="_blank" rel="nofollow"> Results (A Levels) </a></li><li><a href="http://alevel.trinity.edu.np/placements" target="_blank" rel="nofollow"> Placements (A Levels) </a></li><li><a href="http://alevel.trinity.edu.np/testimonials/" target="_blank" rel="nofollow"> Student Views (A Level) </a></li></ul><li className="dropdown-menus">
                    <a href="javascript:void(0)"> Bachelor's</a><ul className="nav-items"><li><a href="https://admissions.trinitycollege.edu.np/?level=bachelor" target="_blank" rel="nofollow"> Online Application </a></li><li><a href="http://bachelor.trinity.edu.np/admission-bachelor/scholarships-bachelor/bbm-tu-scholarship" target="_blank" rel="nofollow"> Scholarship (Bachelor’s) </a></li><li><a href="http://bachelor.trinity.edu.np/results" target="_blank" rel="nofollow"> Results (Bachelor’s) </a></li><li><a href="http://bachelor.trinity.edu.np/placements" target="_blank" rel="nofollow"> Placements (Bachelor’s) </a></li><li><a href="http://bachelor.trinity.edu.np/testimonials/" target="_blank" rel="nofollow"> Student Views (Bachelor's) </a></li></ul></li><ul className="nav-items"><li><a href="https://admissions.trinitycollege.edu.np/?level=bachelor" target="_blank" rel="nofollow"> Online Application </a></li><li><a href="http://bachelor.trinity.edu.np/admission-bachelor/scholarships-bachelor/bbm-tu-scholarship" target="_blank" rel="nofollow"> Scholarship (Bachelor’s) </a></li><li><a href="http://bachelor.trinity.edu.np/results" target="_blank" rel="nofollow"> Results (Bachelor’s) </a></li><li><a href="http://bachelor.trinity.edu.np/placements" target="_blank" rel="nofollow"> Placements (Bachelor’s) </a></li><li><a href="http://bachelor.trinity.edu.np/testimonials/" target="_blank" rel="nofollow"> Student Views (Bachelor's) </a></li></ul></ul></li><li className="dropdown-menus">
                <a href="https://www.trinity.edu.np/news">
                  <i className="far fa-calendar-alt " /> News &amp; Events
                </a>
                <ul className="nav-items"><li><a href="https://www.trinity.edu.np/notice">Notices</a></li><li><a href="https://www.trinity.edu.np/event">Events</a></li><li><a href="https://www.trinity.edu.np/news">News</a></li></ul></li><li className="dropdown-menus">
                <a href="https://www.trinity.edu.np/career" target="_blank" rel="nofollow">
                  <i className="fa fa-user-secret " /> Career
                </a>
                <ul className="nav-items"><li><a href="https://www.trinity.edu.np/career/about-hrs">About HRS</a></li><li><a href="https://www.trinity.edu.np/career/career--faculty">Career - Faculty</a></li><li><a href="https://www.trinity.edu.np/career/career--staff">Career - Staff</a></li><li><a href="https://www.trinity.edu.np/about-trinity/our-people/faculty" target="_blank" rel="nofollow">Current Faculty</a></li><li><a href="https://www.trinity.edu.np/about-trinity/our-people/staff" target="_blank" rel="nofollow">Current Staff</a></li><li><a href="https://www.trinity.edu.np/career/facultys-responsibilities">Faculty's Responsibilities</a></li><li><a href="https://www.trinity.edu.np/career/staffs-general-duties">Staff's General Duties</a></li><li><a href="https://www.trinity.edu.np/career/training--development">Training &amp; Development</a></li><li><a href="https://www.trinity.edu.np/career/attendance">Attendance</a></li><li><a href="https://www.trinity.edu.np/career/routine--duty-hours">Routine &amp; Duty Hours</a></li></ul></li>			</ul>
            <ul className="list-inline social-icons mb-0">
              <li><a href="https://www.facebook.com/Trinity-International-HSSCollege-123877371368846/?fref=ts" target="_blank"><i className="fab fa-facebook-f" /></a></li>
              <li><a href="https://www.instagram.com/trinityinternational2008/" target="_blank"><i className="fab fa-instagram" /></a></li>
              <li><a href="https://www.youtube.com/channel/UCI9QxocOF5Dy5_skkOYIGiA" target="_blank"><i className="fab fa-youtube" /></a></li>
              <li><a href="https://www.linkedin.com/company/89607122/admin/" target="_blank"><i className="fab fa-linkedin-in" /></a></li>
            </ul>
          </div>
        </div>
        <div className="position-relative notice">
          <button className="navbar-toggler" type="button" id="toggle-menu">
            <svg width={29} height={23} viewBox="0 0 29 23" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fillRule="evenodd" clipRule="evenodd" d="M0.183594 22.5644H28.1836V18.93H0.183594V22.5644ZM0.183594 13.4783H28.1836V9.84389H0.183594V13.4783ZM0.183594 0.757812V4.39224H28.1836V0.757812H0.183594Z" fill="#B20000" />
            </svg>
          </button>
        </div>
      </div>

      
        <FooterComponents/>
      </React.Fragment>
  )
}

export default HomeComponents